### ISSUE TITLE
Constraints problem in iOS?

### ISSUE THREAD

**Issue by altondevir** [Rod-at-Rox/RoxXamarinVideo#1]
Hi, 

first, thank you for your work!

I am giving a try to your component and I got stuck in this:

`Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2016-08-23 17:05:06.409 TrashTests.iOS[659:183637] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x12857ae50 h=-&- v=-&- _UIBackdropContentView:0x128031e20.width == _UIBackdropView:0x1285725b0.width>",
    "<NSLayoutConstraint:0x1284a10c0 H:|-(0)-[UIView:0x12844c800]   (Names: '|':_UIBackdropContentView:0x128031e20 )>",
    "<NSLayoutConstraint:0x12853c590 H:[UIView:0x12844c800]-(0)-|   (Names: '|':_UIBackdropContentView:0x128031e20 )>",
    "<NSLayoutConstraint:0x128466b90 H:|-(0)-[_UIBackdropView:0x1285725b0]   (Names: '|':UIView:0x1285798e0 )>",
    "<NSLayoutConstraint:0x128438690 H:[_UIBackdropView:0x1285725b0]-(0)-|   (Names: '|':UIView:0x1285798e0 )>",
    "<NSLayoutConstraint:0x128464a90 H:|-(0)-[UIView:0x1285798e0]   (Names: '|':AVAlphaUpdatingView:0x1285954c0 )>",
    "<NSLayoutConstraint:0x12845b7d0 H:[UIView:0x1285798e0]-(0)-|   (Names: '|':AVAlphaUpdatingView:0x1285954c0 )>",
    "<NSLayoutConstraint:0x12857ce20 H:|-(14)-[AVButton:0x128460530'Done'](LTR)   (Names: '|':UIView:0x12844c800 )>",
    "<NSLayoutConstraint:0x12857cec0 H:[AVButton:0x128460530'Done']-(0)-[UILabel:0x1280bc310'--:--'](LTR)>",
    "<NSLayoutConstraint:0x1285709c0 H:[UILabel:0x1280bc310'--:--'(55)]>",
    "<NSLayoutConstraint:0x12859b2b0 H:[UILabel:0x1280bc310'--:--']-(6)-[AVScrubber:0x128406f10](LTR)>",
    "<NSLayoutConstraint:0x12859b300 AVScrubber:0x128406f10.right == UILabel:0x128585870'--:--'.left - 6>",
    "<NSLayoutConstraint:0x12859b6c0 UILabel:0x128585870'--:--'.right == AVButton:0x128592df0.left>",
    "<NSLayoutConstraint:0x12859b710 H:[UILabel:0x128585870'--:--'(59)]>",
    "<NSLayoutConstraint:0x12859b350 AVButton:0x128592df0.right == UIView:0x12844c800.right - 15>",
    "<NSLayoutConstraint:0x12858bca0 'UIView-Encapsulated-Layout-Width' H:[AVAlphaUpdatingView:0x1285954c0(0)]>"
)`

The controls appear, but the video is not played.

The code I used is pretty simple:

`var videoView = new VideoView {
				Source = ImageSource.FromResource ("TrashTests.Properties.test.mp4")
			};
			MainPage = new ContentPage {
				Content = videoView
			};`

test.mp4 is an embedded resource with the Resource Id = TrashTests.Properties.test.mp4. Using FromUri is also unsatisfactory. 

I added to the AppDelegate the necessary code before the Forms.Init (Rox.VideoIos.Init ();)

Here is a link to the error in iOS for other apparently similar case: http://stackoverflow.com/questions/14327145/unable-to-simultaneously-satisfy-constraints-no-constraints-in-place

Thanks again in advance!

**Comment by Rod-at-Rox** [comment]
Th layout constraints shouldn't stop you from building, just telling you which ones are used and ignored. To play the video, have you called videoView.Start(); or set videoView.AutoPlay=true;

**Comment by altondevir** [comment]
Sorry I forgot to tell that I tried the AutoPlay and start() already. The building is fine, the message comes once the video player is loading in the Application console. Should I set some kind of height or width? Or use some kind of layout? I am not sure what is wrong. That message is all I got.

**Comment by Rod-at-Rox** [comment]
There may be a problem with playing that style of video, due to various issues, can you try to load it into the sample app, or can you make the video you are trying to play available online so I can check

**Comment by altondevir** [comment]
There is no problem with the sample you created. I must be doing something wrong. I will try to find the problem, thanks!

**Comment by altondevir** [comment]
For the ones that may forget it 💃 :

<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>

**Comment by Rod-at-Rox** [comment]
Have a look at https://developer.xamarin.com/guides/xamarin-forms/working-with/images/ if you are using iOS, make sure the resource is set to BuildAction="BundleResource". If still not working let me know and I will check it out,

**Comment by altondevir** [comment]
I actually used this way: 
https://developer.xamarin.com/guides/xamarin-forms/working-with/images/#Embedded_Images
I will try the native way ;)
