### ISSUE TITLE
ImageSource.FromStream not working

### ISSUE THREAD

**Issue by soile1991** [Rod-at-Rox/RoxXamarinVideo#12]
i'm trying to play a video downloaded from url but it won't work
i tried the same code with an image and it works

iVideoView.Source = ImageSource.FromStream(() => new MemoryStream(VideoResponseData));

**Comment by Rod-at-Rox** [comment]
Any particular platform? Is it all platforms? I will be returning around 16-Jan-2017 and will check further then.

**Comment by HilalSener** [comment]
Hi. I tried the same thing. I have a byte array video file. I can return an ImageSource from MemoryStream for images. But what can we do for the video?

**Comment by sethom** [comment]
This is happening to me on iOS as well...

var assembly = typeof(ActivityViewModel).GetTypeInfo().Assembly;
                    ImageSourceConverter imageSourceConverter = new ImageSourceConverter();
                    Stream stream = assembly.GetManifestResourceStream("MyApp.iOS.Resources.Video.Demo1.mov");
                    videoSource = (ImageSource)ImageSource.FromStream(() => stream);

Are there any updates on this?

**Comment by Rod-at-Rox** [comment]
I have not tested older versions, but ImageSource.FromStream works in the latest build
