### ISSUE TITLE
Captions/Subtitles

### ISSUE THREAD

**Issue by JohnGalt1717** [Rod-at-Rox/RoxXamarinVideo#14]
Is it possible to add captioning/subtitle support? All 3 platforms support them so it would be great if we could hook them up properly.

Thanks!

**Comment by Rod-at-Rox** [comment]
I have never had the need for captions or subtitles, and have never looked into it implementing it. I will keep this in mind to check out, and consider implementing. I will be returning around 16-Jan-2017 and have some other things to do, so I'll keep you posted.

**Comment by JohnGalt1717** [comment]
Thank you!

**Comment by JohnGalt1717** [comment]
Also I'd be happy to contribute to this if it was open sourced.

**Comment by Rod-at-Rox** [comment]
Not happening, cc or os
