### ISSUE TITLE
FullScreen

### ISSUE THREAD

**Issue by Aivalo** [Rod-at-Rox/RoxXamarinVideo#2]
Hi Guys,

Is there any way to show the video on full screen with your nuget?

Thanks.
Alvaro.

**Comment by Rod-at-Rox** [comment]
If you are using the built-in controller (ShowController=True) then each platform has a button to make it full screen. If not (ShowController=False), then I can expose a property to allow full screen, but I will not be able to look at this until next week.

**Comment by Rod-at-Rox** [comment]
If have introduced a VideoView.FullScreen boolean property from version 2.1.0-pre3, which is only implemented in UWP, I am hoping to implement for Android and iOS for final 2.1.0 release. I will update progress here.
