### ISSUE TITLE
Still playing

### ISSUE THREAD

**Issue by GuillermoGuevara** [Rod-at-Rox/RoxXamarinVideo#23]
When navigating away from page, the VideoView is still playing but it shouldn't. I think: Can you please make it stop or destroy it when navigating away.

**Comment by Daniel-NP** [comment]
Same problem here, running on Xamarin.iOS. I set the Source to NULL, but the video (and sound) keeps playing.

**Comment by Rod-at-Rox** [comment]
Stop it manually
