### ISSUE TITLE
Player not Visible in UWP Release Build

### ISSUE THREAD

**Issue by wolfgangschneider** [Rod-at-Rox/RoxXamarinVideo#24]
When I compile the Rox.Xamarin.Video.Sample.Uwp in release mode, nothing is visible.

Wolfgang

**Comment by ihassantariq** [comment]
I am having the same issue. @Rod-at-Rox @wolfgangschneider if you guys know anything do let me know.

**Comment by Rod-at-Rox** [comment]
Haven't tested old versions and scenarios, but new build is working
