### ISSUE TITLE
Ducking Background Audio, instead of stopping

### ISSUE THREAD

**Issue by mikehamsa** [Rod-at-Rox/RoxXamarinVideo#25]
Hello,

I'm using the Rox Xamarin video player and it is working very nicely. One question; On android is it possible to have the Video Player request audio focus as AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK? I'd like to allow the user to play background music (with an app like Google Play Music) while my app is using the Rox Xamarin video player to play a video and have the two audio streams play together.

Many Thanks,
Mike...

**Comment by Rod-at-Rox** [comment]
I will look at this as an option
