### ISSUE TITLE
Expose Android HTTP Headers

### ISSUE THREAD

**Issue by JohnGalt1717** [Rod-at-Rox/RoxXamarinVideo#26]
To be able to work with things like Azure Media services etc. you need to be able to pass an HTTP Header for Authorization with Bearer and a token.

Could you expose to Android Http Header options of the android media control please? (and if you want the same on UWP... iOS doesn't have it and you have to hack at it to fix this problem)

**Comment by Rod-at-Rox** [comment]
use httpClient
