### ISSUE TITLE
Can't play video when loaded using stream

### ISSUE THREAD

**Issue by sarthak199526** [Rod-at-Rox/RoxXamarinVideo#27]
I have requirement to play video using stream when I give source to player through stream it shows can't play video while when I used the url to load video it plays fine.I have checked this scenario on android only yet.

Note : I am first download the stream from a public url  of stream and then giving it to player . The same url works when that url given as source to player. I also have check providing the stream of a local stored file to but not working as well

**Comment by Rod-at-Rox** [comment]
Hey mate, The streaming does not work in this version. I did a lot of work getting the remaining items done, but never finished. Last I checked the xam forms team was working on a component, so I stopped. I would suggest going and checking where that is at. Rod

**Comment by sarthak199526** [comment]
Ok great
