### ISSUE TITLE
Video is not playing for iOS in Ad-Hoc distribution mode

### ISSUE THREAD

**Issue by kumargauravhcl** [Rod-at-Rox/RoxXamarinVideo#4]
Hi,
First of all thank you very much for this video player. I am using this nuget for all 3 platform i.e android/ios/windows. It is working fine in android and for iOS when I test my app using debug or release mode, video is playing.
But when I test my app in Ad-hoc mode and download it from secure webserver using a custom plist (attached), the video is not playing. Even I have tried putting a static URL but it doesn't work. Also I put the video in resource folder locally but it is not helping either.
Please see attached custom plist that we are using.

We require it on urgent basis, so it will be great if you let us know the quick solution.

[HCLEngage.zip](https://github.com/Rod-at-Rox/RoxXamarinVideo/files/513176/HCLEngage.zip)

**Comment by Rod-at-Rox** [comment]
[Try_HCLEngage.zip](https://github.com/Rod-at-Rox/RoxXamarinVideo/files/513634/Try_HCLEngage.zip)

I cannot determine if you are you using the plist correctly from the file alone, but if you are trying to access a video from a non-secure location then try the plist I have attached.

**Comment by Rod-at-Rox** [comment]
I have tested a similar deploy which works correctly. The error is either within the loading of the plist, as in not loading the values you think it is, or the control is not being used correctly. I suggest trying to determine the error by simplifying your deploy, even try a default plist, and get that working first. Once you have a simple solution working you can start to introduce your unique deploy properties, one at a time, and test that it still works between modifications.

**Comment by kumargauravhcl** [comment]
I tried the latest pre-release with default plist and it is working fine. Thanks a lot !!!!!!!!!!!!!!!!
