### ISSUE TITLE
Android.Widget.VideoView is left aligned in landscape mode.

### ISSUE THREAD

**Issue by TouchBoarder** [Rod-at-Rox/RoxXamarinVideo#5]
Use a FrameLayout with gravity center for the Android.Widget.VideoView instead of LinearLayout or ReleativeLayout.

**Comment by Rod-at-Rox** [comment]
Thanks dude...  I had another fix, but that one sounds easier, I will try it first, a new version with this fix will be avialable in a few days. Thanks again,

**Comment by Rod-at-Rox** [comment]
FrameLayout did the trick, this available from v2.1.0-pre4.
