### ISSUE TITLE
Exception when navigating away from page

### ISSUE THREAD

**Issue by Lomster** [Rod-at-Rox/RoxXamarinVideo#7]
Hi, thanks for this amazingly useful component.

I am having a problem where when I navigate away from the page containing the in UWP, a NullReferenceException occurs in

   at Xamarin.Forms.Platform.UWP.VisualElementRenderer`2.SetNativeControl(TNativeElement control)
   at Rox.VideoRenderer.<OnElementChanged>d__4.MoveNext()

I have tried everything, including removing the source, disabling the control and removing it from the page

Code in back button handler

```
	async void BackgroundClicked(object sender, EventArgs args)
		{
            try
            {
                await ContentVideo.Stop();
                ContentVideo.Source = null;
                ContentVideo.IsEnabled = false;
                VideoGrid.Children.Remove(ContentVideo);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex);
            }

            await Navigation.PopModalAsync (false);
		}
```

Video player declaration in XAML

`    <roxv:VideoView x:Name="ContentVideo" AutoPlay="True" LoopPlay="False" ShowController="True"></roxv:VideoView>
`

I hope you can help with this

**Comment by Rod-at-Rox** [comment]
So sorry for the delay, I have replicated this issue, unfortunately I will be returning until around 16-Jan-2017, this will be first priority

**Comment by ninianh** [comment]
Hi Lomster, Rod-at-Rox, this is really amazing component.
Related to your issue, i have same error. But i made a workaround and it is working fine now.

       `public MainPage()
        {
           App.Current.UnhandledException += Current_UnhandledException;
        }

        private void Current_UnhandledException(object sender, UnhandledExceptionEventArgs e)
        {
            e.Handled = true;
        }`

**Comment by ninianh** [comment]
I found another problem. When navigating away from page, the VideoView is still playing but it shouldn't. I think: Can you please make it stop or destroy it when navigating away.

**Comment by ChrisMacLeanRQI** [comment]
Any word on a fix for this navigation issue?  Only problem I have run into thus far.  Great tool!

**Comment by deviprasadchinni** [comment]
Is there any solution for this issue., any one please help me.

**Comment by wolfgangschneider** [comment]
Hi please help

In my current issue this is realy a big issue. Where is the replicated issue Rod ad Rox mentioned?  Are there any news or solutions ? 
Or some workarounds 
(ninianh  workaround don't work in debug mode excluding disable all off all AML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION)

Wolfgang

**Comment by Rod-at-Rox** [comment]
Use the work-around mentioned above and stop the video manually
