### ISSUE TITLE
How to fill the full view ?

### ISSUE THREAD

**Issue by tematim** [Rod-at-Rox/RoxXamarinVideo#8]
Hello,

The control is very good, no more platform renderer needed.

I have a question, how to fill the full view to remove black lines near the video ?

For MPMoviePlayerController it's _moviePlayer.ControlStyle = MPMovieControlStyle.Embedded.

Regards

**Comment by Rod-at-Rox** [comment]
Hi, the later versions use AVPlayer for iOS, I will have to check exactly what you are referring to. I will be returning around 16-Jan-2017 and will update further then.

**Comment by adamlonsdale** [comment]
Also interested in this. Wondering if this is a closed-source project or if you would be open to sharing your code so I could write my own version?
